### ISSUE TITLE
handle tree sitter nodes with the same starting location

### ISSUE THREAD

**Issue by wstevick** [ggandor/leap-ast.nvim#4]
I have discovered that often, two nodes have the same starting location. This happens when one is the first child of the other. For instance, ```lua
local function something()
    if sometest() then
        function_in_if()
    end
    other_function()
end
```
If you're cursor is on `function_in_if`, there's not way to select just the if-block without selecting the entire function body.

**Comment by ggandor** [comment]
Yes, I don't think this can be solved in a satisfying way. See also https://github.com/mfussenegger/nvim-treehopper/issues/23#issuecomment-1304466300, and the whole discussion above/below.

**Comment by wstevick** [comment]
Okay. Thanks anyway.
